server:
  port: 8080
  servlet:
    context-path: /assistant

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/assistant"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  # Redis configuration that matches RedisConfig class expectations
  redis:
    host: localhost
    port: 6379
    password: # leave empty if no password
    timeout: 60000
  mail:
    host: smtp.gmail.com
    port: 587
    username: nhatthaitn2003@gmail.com
    password: rdqg grmt jwoj retl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Flyway configuration for database migrations
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

# Application specific settings
app:
  # Frontend URL for verification links
  frontend:
    url: http://localhost:5173
  
  # Verification token settings
  verification:
    token:
      expiration: 900 # 15 minutes (in seconds)
  
  # JWT Settings
  jwt:
    # Secret key for signing the JWT tokens
    secret: yrU537DGFdf743hgfKJHGF8743hgDFG9876HGDF7846hgKJHGD7846hfH
    # Access token expiration time in milliseconds (15 minutes)
    access-token-expiration: 604800000
    # Refresh token expiration time in milliseconds (7 days)
    refresh-token-expiration: 604800000

  # Facebook Bot Configuration
  facebook:
    api:
      url: https://graph.facebook.com/v18.0
  
  # Base URL for webhooks
  base:
    url: ${BASE_URL:http://localhost:8080/assistant}

  # BNB Testnet settings
  bnb:
    testnet:
      url: ${BNB_TESTNET_URL:https://data-seed-prebsc-1-s1.binance.org:8545/}
      backup-url: ${BNB_TESTNET_BACKUP_URL:https://data-seed-prebsc-2-s1.binance.org:8545/}
    main-wallet-address: ${MAIN_WALLET_ADDRESS:0x78dc09e108f3a7c73ed6a8ba7b09b278c1da5cf6}  # Replace with your main wallet address
    gas-limit: ${GAS_LIMIT:21000}
    gas-price: ${GAS_PRICE:20000000000}  # 20 Gwei
    
  # Exchange rate settings
  exchange-rate:
    usd-to-vnd: ${USD_TO_VND_RATE:26000}  # 1 USD = 26,000 VND

# VNPAY Configuration
vnpay:
  version: 2.1.0
  tmnCode: 5SGAW8CS
  hashSecret: 4WG189P4KMM9CGLQLJUFCKL866XXU9SV
  paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:5173/payment/result
  returnIPNUrl: http://localhost:5173/api/vnpay/ipn
  timezone: Asia/Ho_Chi_Minh