CREATE TABLE IF NOT EXISTS facebook_access_tokens (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    access_token VARCHAR(2000) NOT NULL,
    verify_token VARCHAR(255),
    webhook_url VARCHAR(255),
    active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_facebook_shop_id (shop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 